In [1]:
from sympy import *
init_printing()
from sympy.matrices import *
from numpy import *

In [3]:
M = Matrix([[1,0,0], [0,0,0]])
M

?1  0  0?
?       ?
?0  0  0?

In [5]:
Matrix([M, (0,0,-1)])

?1  0  0 ?
?        ?
?0  0  0 ?
?        ?
?0  0  -1?

In [7]:
Matrix(2, 3, [1,2,3,4,5,6]) #2 by 3 matrix with these values

?1  2  3?
?       ?
?4  5  6?

In [9]:
Matrix(4, 7, arange(28).astype(int))

?0.0   1.0   2.0   3.0   4.0   5.0   6.0 ?
?                                        ?
?7.0   8.0   9.0   10.0  11.0  12.0  13.0?
?                                        ?
?14.0  15.0  16.0  17.0  18.0  19.0  20.0?
?                                        ?
?21.0  22.0  23.0  24.0  25.0  26.0  27.0?

In [11]:
#create eye matrix
def eye(i, j):
    if i == j:
        return 1
    else:
        return 0

Matrix(4, 4, eye)

?1  0  0  0?
?          ?
?0  1  0  0?
?          ?
?0  0  1  0?
?          ?
?0  0  0  1?

In [14]:
Matrix(3, 4, lambda i, j: 1 - (i+j) % 2)

?1  0  1  0?
?          ?
?0  1  0  1?
?          ?
?1  0  1  0?

In [19]:
eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [20]:
zeros(2)

array([ 0.,  0.])

In [34]:
#zeros(5, 2) #doesn't work??

In [30]:
ones(3)

array([ 1.,  1.,  1.])

In [34]:
#ones(1, 5) #doesn't work??

In [34]:
diag(1, Matrix([1,2], [3,4]))

TypeError: Data type not understood

In [1]:
from sympy import *
init_printing()